stages:
  - build

image: docker:latest
services:
  - docker:dind

variables:
  CONTAINER_REGISTRY: 'registry.gitlab.com/luisnabais/ansible-runner'
  DOCKER_REGISTRY: 'luisnabais/ansible-runner'
  BUILDX_VERSION: "v0.8.2"
  BUILDX_URL: "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64"
  BUILDX_PLATFORMS: "linux/amd64,linux/arm64/v8"


docker-build.alpine:
  stage: build
  before_script:
    - wget -O /usr/bin/docker-buildx ${BUILDX_URL}
    - chmod +x /usr/bin/docker-buildx
    - docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
    - docker login -u ${CONTAINER_REGISTRY_USER} -p ${CONTAINER_REGISTRY_TOKEN} ${DOCKER_ENV_CI_REGISTRY}
  script:
    - ALPINE_TAG=$(grep FROM Dockerfile.alpine | cut -d' ' -f2 | tr -d ':')
    - docker-buildx create --use
    - docker buildx build
      -f Dockerfile.alpine
      --platform ${BUILDX_PLATFORMS}
      --tag ${CONTAINER_REGISTRY}:${ALPINE_TAG}-${CI_COMMIT_TAG}
      --tag ${CONTAINER_REGISTRY}:alpine-${CI_COMMIT_TAG}      
      --tag ${CONTAINER_REGISTRY}:${CI_COMMIT_TAG}
      --tag ${CONTAINER_REGISTRY}:alpine
      --tag ${CONTAINER_REGISTRY}:latest
      --push
      .
  rules:
    - if: $CI_COMMIT_TAG