stages:
  - build

variables:
  DOCKER_REGISTRY: 'luisnabais/ansible-runner'
  BUILDX_VERSION: "v0.12.0"
  BUILDX_URL: "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64"
  BUILDX_PLATFORMS: "linux/amd64,linux/arm64/v8"

container-build.alpine:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - wget -O /usr/bin/docker-buildx ${BUILDX_URL}
    - chmod +x /usr/bin/docker-buildx
    - docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - ALPINE_TAG=$(grep FROM Dockerfile.alpine | cut -d' ' -f2 | tr -d ':')
    - docker-buildx create --use
    - docker buildx build
      --provenance=false
      -f Dockerfile.alpine
      --platform ${BUILDX_PLATFORMS}
      --tag ${CI_REGISTRY_IMAGE}:${ALPINE_TAG}-${CI_COMMIT_TAG}
      --tag ${CI_REGISTRY_IMAGE}:alpine-${CI_COMMIT_TAG}      
      --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
      --tag ${CI_REGISTRY_IMAGE}:alpine
      --tag ${CI_REGISTRY_IMAGE}:latest
      --tag ${DOCKER_REGISTRY}:${ALPINE_TAG}-${CI_COMMIT_TAG}
      --tag ${DOCKER_REGISTRY}:alpine-${CI_COMMIT_TAG}
      --tag ${DOCKER_REGISTRY}:${CI_COMMIT_TAG}
      --tag ${DOCKER_REGISTRY}:alpine
      --tag ${DOCKER_REGISTRY}:latest
      --push
      .
  rules:
    - if: $CI_COMMIT_TAG