stages:
  - build

image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_REPO: 'luisnabais/ansible-runner'
  BUILDX_VERSION: "v0.8.2"
  BUILDX_URL: "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64"
  BUILDX_PLATFORMS: "linux/amd64,linux/arm64/v8"


docker-build.alpine:
  stage: build
  before_script:
    - wget -O /usr/bin/docker-buildx ${BUILDX_URL}
    - chmod +x /usr/bin/docker-buildx
    - docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
  script:
    - ALPINE_TAG=$(grep FROM Dockerfile.alpine | cut -d' ' -f2 | tr -d ':')
    - docker-buildx create --use
    - docker buildx build
      -f Dockerfile.alpine
      --platform ${BUILDX_PLATFORMS}
      --tag ${DOCKER_REPO}:${ALPINE_TAG}-${CI_COMMIT_TAG}
      --tag ${DOCKER_REPO}:alpine-${CI_COMMIT_TAG}      
      --tag ${DOCKER_REPO}:${CI_COMMIT_TAG}
      --tag ${DOCKER_REPO}:alpine
      --tag ${DOCKER_REPO}:latest
      --push
      .
  rules:
    - if: $CI_COMMIT_TAG